person/loginapp/urls.py
from django.urls import path 
from . views import index,success,view
app_name='loginapp'
urlpatterns=[
    path('',index,name='sign'),
    path('check/',success,name='success'),
    path('view',view,name='view'),
]

person/person/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('loginapp.urls'))
]

person/loginapp/models.py
from django.db import models

# Create your models here.
class Details(models.Model):
    firstname=models.CharField(max_length=30)
    lastname=models.CharField(max_length=30)
    username=models.CharField(max_length=30,null=True)
    email=models.CharField(max_length=30)
    password=models.CharField(max_length=20)
    address=models.CharField(max_length=100,null=True)
    state=models.CharField(max_length=20)
    city=models.CharField(max_length=20)
    choices=[('Doctor','Doctor'),('Patient','Patient')]
    pincode=models.CharField(max_length=10,default='0')
    typeofperson=models.CharField(choices=choices,max_length=10)

    def __str__(self):
       return  self.email

person/loginapp/views.py
from django.shortcuts import render
from . models import Details
# Create your views here.
def index(request):
    return render(request,'loginapp/one.html')
def success(request):
    request.POST.get('')
    firstname=request.POST.get('firstname')
    lastname=request.POST.get('lastname')
    username=request.POST.get('username')
    email=request.POST.get('email')
    password=request.POST.get('password')
    state=request.POST.get('sender')
    city=request.POST.get('city')
    address=request.POST.get('address')
    pincode=request.POST.get('pincode')
    if(Details.objects.filter(firstname=firstname,lastname=lastname,email=email,password=password)):
        return render(request,'loginapp/one.html')
    else:
        Details.objects.create(firstname=firstname,lastname=lastname,email=email,username=username,password=password,state=state,city=city,address=address,pincode=pincode)
            
        return render(request,'loginapp/success.html')
def view(request):
    doctor=Details.objects.filter(typeofperson='Doctor')
    patient=Details.objects.filter(typeofperson='Patient')
    return render(request,'loginapp/Doctorpatient.html',{'doctor':doctor,'patient':patient})

person/loginapp/templates/loginapp/Doctorpatient.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%load static%} 
    <link rel="stylesheet" href="{%static 'loginpage/css/hold.css'%}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
      <div class="container1">
          <div style="text-align: center;">DashBoard</div>

          <div class="containgroups">
            <div class="insidetable">
              <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Doctors">DT</th>
                    <th scope="col" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Email of doctor">ED</th>
                    <th scope="col" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Patients">PT</th>
                    <th scope="col" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Email of patient">EP</th>
                  </tr>
                </thead>
                
                {% for values in doctor %}
                  {%csrf_token%}
                <tbody>
                  <tr>
                    <th scope="row">{{values.firstname}} {{values.lastname}}</th>
  
                    <td>{{values.email}}</td>
                
  
                  </tr>
                </tbody>
                  {% endfor %}
                {% for values in person %}
                  {%csrf_token%}
                <tbody>
                  <tr>
                    <th scope="row">{{values.firstname}} {{values.lastname}}</th>
  
                    <td>{{values.email}}</td>
                
  
                  </tr>
                </tbody>
                  {% endfor %}
              </table>
            </div>
            
          </div>
      </div>
  </body>
</html>

person/loginapp/templates/loginapp/one.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    {% load static%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'loginapp/css/one.css' %}" type='text/css'>
</head>
<body> 
    <div class="container">
       <a href="{% url 'loginapp:view'%}"><button class="btn btn-sm btn-primary" style="margin-left: 500px; margin-right: 500px;" >View All</button></a> 
        <form action='/check' method='POST'>
            {%csrf_token%}
            <div class="mb-3">
                <label for="firstname" class="form-label">First Name</label>
                <input type="text" class="form-control" id="firstname" name="firstname">
            </div>
            <div class="mb-3">
                <label for="lastname" class="form-label">Last Name</label>
                <input type="text" class="form-control" id="lastname" name="lastname">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">User Name</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" name="email">
            </div>
            <div class="mb-3" id="pass">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name='password'>
            </div>
            <div class="mb-3 confirm" id="cpass" >
                <label for="confirmpassword" class="form-label">Confirm Password</label>
                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword">
            </div>
             <script src="{%static 'loginapp/js/one.js'%}"></script>
            <div class="mb-3">
                <label for="address" class="form-label">Address</label>
                <input type="text" class="form-control" id="address" name="address">
              </div>
              <div class="mb-3">
                <label for="state" class="form-label">State</label>
                <input type="text" class="form-control" id="state" name="state">
              </div>
            <div class="row">
                <div class="col">
                    <div class="mb-3 assig">
                        <input type="text" class="form-control" id="type" placeholder="Type" readonly>
                    </div>
                </div>
                <div class="col" name="state">
                    <select name="sender" class="form-select assig" aria-label="Default select example" >
                        <option selected>Select</option>
                        <option value="Patient" >Patient</option>
                        <option value="Doctor">Doctor</option>
                    </select>
                </div>
            </div>
            <div class="mb-3">
                <label for="city" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name="city">
              </div>
              <div class="mb-3">
                <label for="pincode" class="form-label">Pincode</label>
                <input type="number" class="form-control" id="pincode" name="pincode">
              </div>
            <button type="submit" class="btn btn-primary" value="confirm">Submit</button>
          </form>
    </div>
        
    
  </body>
</html>

person/loginapp/templates/loginapp/success.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    {% load static%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'loginapp/css/one.css' %}" type='text/css'>
</head>
<body> 
    <div class="container">
       
  </body>
</html>